const db = require('../models');

const getData = async () => {
  try {
    let prodsSeed = [];
    for (let prod of products) {
      const product = {
        id: prod[0],
        product_name: prod[1],
        ingredients: prod[4],
        amount: prod[5],
        price: prod[7],
        img_link: prod[8],
      };
      await db.Unit.findOne({where: {unit: prod[6]}})
        .then(res => product.unit_id = res.dataValues.id)
        .catch();
      await db.Manufacture.findOne({where: {manufacture: prod[2]}})
        .then(res => product.manufacture_id = res.dataValues.id)
        .catch();
      await db.Category.findOne({where: {category: prod[3]}})
        .then(res => product.category_id = res.dataValues.id)
        .catch();
      await prodsSeed.push(product);
    }
    return prodsSeed;
  } catch (err) {
    console.log(err);
  }
};

const products = [
  ['45004252', 'THOUSAND ISLAND DRESSING', 'Aldi-Benner Company', 'Sauces', 'SOYBEAN OIL, WATER, TOMATO PUREE (WATER, TOMATO PASTE), SUGAR, VINEGAR, EGG YOLKS, SALT, CONTAINS LESS THAN 2% OF: CUCUMBERS, HIGH-FRUCTOSE CORN SYRUP, SPICE, ONION*, XANTHAN GUM, RED BELL PEPPERS*, CITRIC ACID, POTASSIUM SORBATE AND CALCIUM DISODIUM EDTA AS PRESERVATIVES, PAPRIKA (COLOR), NATURAL FLAVOR.', 92805, '0.25 kg', 95, 'https://www.wish-bone.com/sites/g/files/qyyrlu681/files/images/products/thousand-island-dressing-02307.png'],
  ['45052469', 'MANGO', 'American Importing Co. Inc.', 'Fruits & Vegetables', 'MANGO, SUGAR, CITRIC ACID, CALCIUM CHLORIDE (FOR PRODUCT TEXTURE), SULFUR DIOXIDE (TO PRESERVE COLOR), NATURAL FLAVOR, COLORED WITH (YELLOW 5, YELLOW 6).', 93846, '1 kg', 7, 'https://premier-parfum-pp.ua/image/cache/catalog/originaly/81-499x455.png'],
  ["45187468",	"COFFEE BEANS",	"Aqualink Nevada, LLC",	"Tea & Coffee",	"COFFEE BEANS",	8676,	"1 pack",	36,	"https://adorecoffee.com.au/wp-content/uploads/2019/09/dw-boutique-coffee-roasters-australia-sydney-bag_beans-2.png"],
  ["45022230",	"GREEN TEA",	"ARGO TEA",	"Tea & Coffee",	"Camellia sinensis leaves",	64624,	"0.5 kg",	64,	"https://www.tazo.com/sk-eu/content/dam/brands/tazo/specified_clusterscountries/1716988-794522001545-05.png.rendition.470.470.png"],
  ["45233756",	"AVOCADO",	"AVEYO",	"Fruits & Vegetables",	"HASS AVOCADO, WHITE VINEGAR, OLIVE OIL, SEA SALT, LIME JUICE",	91668,	"1 kg",	16,	"https://mission-produce-static.sfo2.cdn.digitaloceanspaces.com/craft/page-content-images/image-1/mission-europe/avocado-spread.png"],
  ["45181259",	"HAM STEAK",	"Big Y Foods, Inc.",	"Meat & Seafood",	"CURED WITH: WATER, SALT, DEXTROSE, BROWN SUGAR, CONTAINS 2% OR LESS OF SODIUM PHOSPHATE, SODIUM ERYTHORBATE, FLAVORINGS, SODIUM PROPIONATE, SODIUM BENZOATE, SODIUM NITRITE.",	90513,	"1 kg",	86,	"https://az810478.vo.msecnd.net/media/images/default-source/Products/ham/7-oz-ham-steak.png"],
  ["45181265",	"APPLES",	"Big Y Foods, Inc.",	"Fruits & Vegetables",	"APPLES.",	54233,	"1 kg",	30,	"https://riola.ua/wp-content/uploads/2018/11/fuji_500.png"],
  ["45363197",	"GALA APPLES",	"BJ's Wholesale Club / Corporate Brands",	"Fruits & Vegetables",	"GALA APPLES",	47439,	"1 kg",	94,	"https://freeticketmall.com/wp-content/uploads/thumbs_dir/fresh-apple-royal-gala-pack-of-4-nos-1-pc-2-nubs959jiawza1wut0ryz0nnhva53vycwi83nolxkc.png"],
  ["45267494",	"ONION",	"Blazing Bagels and Bakery, Inc.",	"Fruits & Vegetables",	"SHEPHERD'S GRAIN UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, BROWN CANE SUGAR (SUGAR, INVERT SUGAR, CANE MOLASSES), MALTED BARLEY FLOUR, DEHYDRATED ONION, CONTAINS 2% OF EACH OF THE FOLLOWING: SEA SALT, CORN MEAL, YEAST, CALCIUM SULFATE, ENZYMES (PLANT BASED).",	66275,	"1 kg",	73,	"https://soobrand.com/wp-content/uploads/2019/04/box_onion.png"],
  ["45004761",	"ALMONDS",	"Blue Diamond Growers",	"Fruits & Vegetables",	"ALMONDS, SUGAR, VEGETABLE OIL (CANOLA, SAFFLOWER AND/OR SUNFLOWER), HONEY, CINNAMON, SEA SALT AND CORN MALTODEXTRIN.",	61656,	"0.3 kg",	7,	"https://balticfresh.com/image/cache/catalog/PRODUCTS/1021L.-800x800.png"],
  ["45212519",	"CRABMEAT",	"BLUE STAR",	"Meat & Seafood",	"CRABMEAT (BLUE SWIMMING CRAB - PORTUNUS PELAGICUS) AND SODIUM ACID PYROPHOSPHATE (TO RETAIN COLOR)",	20986,	"0.5 kg",	68,	"https://ryboedov.ru/upload/iblock/b87/b87876df1d67421e36636846601097dc.png"],
  ["45002250",	"MILK",	"Borden Dairy Company",	"Beverages",	"MILK, HIGH FRUCTOSE CORN SYRUP, SUGAR, NONFAT DRY MILK, CORN STARCH, COCOA, COCOA (PROCESSED WITH ALKALI), SALT, CARRAGEENAN, NATURAL AND ARTIFICIAL FLAVOR, VITAMIN D3",	95412,	"1.6 L",	33,	"https://www.stonyfield.com/wp-content/uploads/2017/02/stonyfield-organic-milk-halfgallon-wholemilk-500x500.png"],
  ["45114846",	"TURKEY BACON",	"Butterball, LLC",	"Meat & Seafood",	"POULTRY INGREDIENTS (TURKEY, MECHANICALLY SEPARATED TURKEY), WATER, SALT, SUGAR, CONTAINS 2% OR LESS OF CANOLA OIL, SUNFLOWER OIL, NATURAL FLAVOR, SODIUM PHOSPHATE, SODIUM ERYTHORBATE, SODIUM NITRITE.",	860,	"1 kg",	94,	"https://www.jfmmeats.com/wp-content/uploads/2019/08/Turkey-Bacon-VP-31393.png"],
  ["45004188",	"CHEDDAR CHEESE - EXTRA SHARP",	"CABOT CREAMERY COOPERATIVE",	"Dairy, Eggs & Cheese",	"FRESH PASTEURIZED MILK, CHEESE CULTURES, SALT, ENZYMES, ANNATTO (IF COLORED).",	37058,	"0.226 kg",	88,	"https://thebigcheese.com/wp-content/uploads/2020/11/Product-Group-1-600x386.png"],
  ["45048202",	"PAR SKIM MILK CHEESE",	"CHAPALA",	"Dairy, Eggs & Cheese",	"CULTURED PASTEURIZED GRADE A MILK AND SKIM MILK, SEA SALT AND ENZYMES.",	66190,	"1 pack",	24,	"https://galbanicheese.com/wp-content/uploads/2019/09/Galbani-Shredded-Asiago-Parmesan-6oz-72DPI-1.png"],
  ["45212532",	"CLASSIC HUMMUS",	"Completely Fresh Foods, Inc",	"Sauces",	"COOKED GARBANZO BEANS (GARBANZO BEANS (CHICKPEAS), WATER), TAHINI (GROUND SESAME), NON-FAT GREEK YOGURT (CULTURED PASTEURIZED GRADE A NON FAT MILK, SKIM MILK AND PECTIN), CULTURED DEXTROSE (ADDED FOR FRESHNESS), GARLIC POWDER, LEMON JUICE, CITRIC ACID, SALT, SPICES, GUAR GUM.",	10994,	"1 pack",	77,	"https://cdn.shopify.com/s/files/1/0006/6270/0079/products/ClassicHummusFront_300x.png?v=1593794147"],
  ["45004000",	"EXTRA VIRGIN OLIVE OIL",	"Delhaize America, Inc.",	"Sauces",	"EXTRA VIRGIN OLIVE OIL.",	34789,	"0.48 kg",	86,	"https://i5.walmartimages.com/asr/0417fed9-29f1-47c1-a309-15797f6a6852.6cdc3807bb39ae83d77c055836ba215c.png?odnWidth=612&odnHeight=612&odnBg=ffffff"],
  ["45041521",	"MILK CHOCOLATE",	"DISNEY",	"Sweets",	"SUGAR, COCOA BUTTER, CHOCOLATE LIQUOR, MILK, SOY LECITHIN AND PGPR (EMULSIFIERS), VANILLA, SALT.",	28780,	"1 pack",	75,	"https://images.ua.prom.st/440451267_shokolad-schogetten-alpine.jpg"],
  ["45054001",	"PORK",	"DOGFISH HEAD RAISON D'ETRE",	"Meat & Seafood",	"PORK RAISED WITHOUT ANTIBIOTICS, BEER, CONTAINS LESS THAN 2% OF BROWN SUGAR, WHITE ONION, WATER, SALT, VINEGAR, SPICES (INCLUDING MUSTARD), YEAST EXTRACT, NATURAL FLAVORS, IN A NATURAL PORK CASING.",	32468,	"1 kg",	32,	"https://www.smithfield.com/wp-content/uploads/smithfield-boneless-pork-sirloin-product-620x450.png"],
  ["45186685",	"HIMALAYAN PINK SALT",	"DVC Industries, Inc",	"Grains, Pasta & Sides",	"HIMALAYAN PINK SALT.",	9008,	"1 kg",	4,	"https://www.geo-fresh.com/wp-content/uploads/2018/09/Himalayan-Pink-Salt-front-A.png"],
  ["45018790",	"BUTTER",	"Emixshow Magazine, Inc.",	"Dairy, Eggs & Cheese",	"BUTTER (CULTURED CREAM), WHITE SPRING TRUFFLES (TUBER ALBIDUM PICO), SALT AND FLAVORING.",	89281,	"0.5 kg",	37,	"https://www.flora.com/en-us/floraplant/-/media/project/upfield/brands/flora/flora-plant-us/assets/products/flora-plant-butter-unsalted-usa.png?w=500&hash=380DF46810E523E418598CB8D1413835"],
  ["45049787",	"FLOUR",	"FABI SAA",	"Grains, Pasta & Sides",	"FLOUR",	51949,	"1 kg",	2,	"https://cdn.shopify.com/s/files/1/2522/4972/products/tapioca-flour-starch-7151802183-A_preview.png?v=1514521688"],
  ["45203101",	"WINGS",	"FAMILY FAVORITES",	"Meat & Seafood",	"CHICKEN BREAST WITH RIB MEAT, WATER, MODIFIED FOOD STARCH, SALT, SODIUM PHOSPHATE. BATTERED WITH: WATER, ENRICHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), SALT, WHEY, LEAVENING (SODIUM, ALUMINUM PHOSPHATE, SODIUM BICARBONATE), SPICE, GARLIC POWDER, OLEORESIN PAPRIKA. BREADED WITH: ENRICHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), SALT, DEXTROSE, LEAVENING (SODIUM BICARBONATE, SODIUM ACID PYROPHOSPHATE, MONOCALCIUM PHOSPHATE), MONOGLYCERIDES, PARTIALLY HYDROGENATED SOYBEAN OIL, OLEORESIN PAPRIKA, BREADING SET IN VEGETABLE OIL. COATED WITH: HIGH FRUCTOSE CORN SYRUP, TOMATO PASTE, DISTILLED VINEGAR, WATER, CORN SYRUP, HONEY, MOLASSES, SALT, CONTAINS LESS THAN 2% OF THE FOLLOWING: MUSTARD BRAN, NATURAL HICKORY SMOKE FLAVOR, SPICES, NATURAL FLAVOR, ONION POWDER, GARLIC POWDER, SODIUM BENZOATE, CARAMEL COLOR, SUGAR.",	32123,	"1 kg",	63,	"https://www.flamingo.ca/wp-content/uploads/2018/03/806-8657_Ailes_Crispy-Spicy_650g_ENG.png"],
  ["45203109",	"CHICKEN BREAST NUGGETS",	"FAMILY FAVORITES",	"Meat & Seafood",	"GROUND CHICKEN BREAST WITH RIB MEAT, WATER, MODIFIED FOOD STARCH, SALT, SODIUM PHOSPHATE, BATTERED WITH WATER, ENRICHED WHEAT FLOUR (ENRICHED WITH NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), SALT, WHEY, LEAVENING (SODIUM ALUMINUM PHOSPHATE, SODIUM BICARBONATE), SPICE, GARLIC POWDER, OLEORESIN PAPRIKA. BREADED WITH: ENRICHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), SALT, DEXTROSE, LEAVENING (SODIUM BICARBONATE, SODIUM ACID PYROPHOSPHATE, MONOCALCIUM PHOSPHATE), MONOGLYCERIDES, PARTIALLY HYDROGENATED SOYBEAN OIL, OLEORESIN PAPRIKA, BREADING SET IN VEGETABLE OIL.",	86388,	"1 kg",	14,	"https://nomadfoodscdn.com/-/media/project/bluesteel/birdseye-uk/0-products-packshots/chicken-packshots/chicken-pieces-2019/150719_22_glutenfree_chicken-nuggets_nomumsnet_470x300.png"],
  ["45041505",	"FERRERO ROCHER, FINE HAZELNUT CHOCOLATES",	"Ferrero U.S.A., Incorporated",	"Sweets",	"MILK CHOCOLATE (SUGAR, COCOA BUTTER, COCOA MASS, SKIM MILK POWDER, BUTTEROIL, LECITHIN AS EMULSIFIER (SOY), VANILLIN: AN ARTIFICIAL FLAVOR), HAZELNUTS, SUGAR, PALM OIL, WHEAT FLOUR, WHEY (MILK), LOWFAT COCOA POWDER, LECITHIN AS EMULSIFIER (SOY), SODIUM BICARBONATE AS LEAVENING AGENT, SALT, VANILLIN: AN ARTIFICIAL FLAVOR.",	96463,	"1 pack",	19,	"https://s.alicdn.com/@sc01/kf/U6c705929ed8445a2a886dd4345f11292z.png"],
  ["45048167",	"FRESH POTATOES",	"Flora's Distributors, Inc.",	"Fruits & Vegetables",	"FRESH POTATOES FLAKES 86%, WHEAT FLOUR TYPE 00, POTATO STARCH, SALT, RICE FLOUR, ACIDITY REGULATOR, LACTIC ACID(E270)', PRESERVATIVE: SORBIC ACID(E200), FLAVOR.",	94865,	"1 kg",	52,	"https://www.pngkey.com/png/full/36-368698_buona-compagnia-gourmet-uses-fresh-potatoes-peeled-peeled.png"],
  ["45001658",	"FETTUCCINE",	"FRESH & EASY",	"Grains, Pasta & Sides",	"DURUM WHEAT SEMOLINA, NIACIN, FERROUS SULFATE (IRON), THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID.",	37836,	"1 pack",	68,	"https://www.dececco.com/wp-content/uploads/2018/05/0UW0303-FETTUCCINE-3.png"],
  ["45001660",	"SPAGHETTI",	"FRESH & EASY",	"Grains, Pasta & Sides",	"DURUM WHEAT SEMOLINA, NIACIN, FERROUS SULFATE (IRON), THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID.",	92758,	"0.3 kg",	23,	"https://pastaespaghetti.com/wp-content/uploads/2016/07/Spaghetti-al-Germe-di-Grano-500gr-%E2%80%93-Pastificio-Morelli.png"],
  ["45001657",	"THIN SPAGHETTI",	"FRESH & EASY",	"Grains, Pasta & Sides",	"DURUM WHEAT SEMOLINA, NIACIN, FERROUS SULFATE (IRON), THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID.",	40429,	"0.3 kg",	24,	"https://d17tib1obgwsvh.cloudfront.net/american-beauty/wp-content/uploads/sites/9/2019/02/AB_Thin-Spaghetti-16-oz.png"],
  ["45001548",	"REAL MAYONNAISE MADE WITH CIDER VINEGAR",	"FRESH & EASY",	"Sauces",	"SOYBEAN OIL, EGGS, CIDER VINEGAR, WATER, CONTAINS LESS THAN 2% OF: SALT, SPICE, LEMON JUICE CONCENTRATE, NATURAL FLAVORS.",	28939,	"1 pack",	24,	"https://ketoandorganic.com/wp-content/uploads/2020/07/HG_Mayo_630g_FOP.png"],
  ["45001628",	"ICE CREAM, GELATO",	"FRESH & EASY",	"Sweets",	"WHOLE MILK, CREAM, SUGAR, GLUCOSE SYRUP, COCONUT FLOUR, WATER, NATURAL FLAVOR, CORN STARCH, SKIM MILK POWDER, CITRIC ACID, FUDGE (SUGAR, CANOLA OIL, COCOA, SKIM MILK POWDER, SOY LECITHIN), MONO- AND DI-GLYCERIDES, CARRAGEENAN, GUAR GUM, LOCUST BEAN GUM.",	8858,	"0.5 kg",	7,	"https://www.selectaphilippines.com/content/dam/unilever/carte_d_or/philippines/pack_shot/4800086043726-1386658-png.png"],
  ["45089346",	"WILD DANDELION HONEY",	"Georgia Peach Products, Inc.",	"Sweets",	"RAW DANDELION HONEY",	41922,	"0.5 kg",	87,	"https://cdn3.volusion.com/ysaxx.exycl/v/vspfiles/photos/124196-2.png?v-cache=1484562738"],
  ["45209720",	"CUT LEAF SPINACH",	"Giant Eagle, Inc.",	"Fruits & Vegetables",	"SPINACH.",	3176,	"0.3 kg",	82,	"https://www.checkers.co.za/medias/10144928EA-20190726-Media-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wzOTA1OTR8aW1hZ2UvcG5nfGltYWdlcy9oNzUvaDNiLzg4NTc0NTcyMjk4NTQucG5nfDM2NDZjNzkxZTgyZTZhMTg1NTc3ZGJkY2NkNWE4NjE0ZTllM2EzNzkyMzBiZjkzNzA2ZGI3NWJkY2Y5NWU5YTA"],
  ["45209721",	"WHOLE BABY CARROTS",	"Giant Eagle, Inc.",	"Fruits & Vegetables",	"CARROTS.",	28911,	"1 kg",	91,	"https://www.orogel.it/media/immagini/2683_n_CAROTINE-INTERE.png"],
  ["45209717",	"LEAF SPINACH",	"Giant Eagle, Inc.",	"Fruits & Vegetables",	"SPINACH.",	95309,	"0.3 kg",	22,	"https://organiclivestockandcrops.org/wp-content/uploads/2018/09/organic-spinach.png"],
  ["45041514",	"GODIVA, ASSORTED BELGIAN CHOCOLATE",	"Godiva Chocolatier, Inc.",	"Sweets",	"SWEETENED CONDENSED MILK, BUTTER (UNSALTED), SUGAR, HIGH FRUCTOSE CORN SYRUP, COCOA BUTTER, UNSWEETENED CHOCOLATE PROCESSED WITH ALKALI, MILK POWDER, UNSWEETENED CHOCOLATE, CORN SYRUP, PALM OIL, SKIM MILK POWDER, SORBITOL, BUTTER OIL, NATURAL FLAVOR, SKIM MILK, INVERT SUGAR, CARAMEL, HEAVY CREAM, EMULSIFIER (SOY LECITHIN), BUTTER OIL (MILK), WATER, STRAWBERRY POWDER, GLYCERIN, BREAKFAST COCOA, BUTTER (SALTED), INVERTASE, CORN STARCH, ANTIOXIDANT (TOCOPHEROLS), SALT, BAKING SODA, CHERRY JUICE CONCENTRATE, ALMONDS, MOLASSES, PRESERVATIVE (POTASSIUM) SORBATE), VANILLA POWDER, ARTIFICIAL FLAVOR, CARAMEL COLOR, CITRIC ACID.",	42027,	"1 pack",	85,	"https://d3tft74pg0cmwk.cloudfront.net/cache/800/0/godivauk/catalog/product/7/2/72811_alt1.png"],
  ["45004264",	"BROWN RICE",	"Goya Foods, Inc.",	"Grains, Pasta & Sides",	"LONG GRAIN BROWN RICE.",	41171,	"0.5 kg",	12,	"https://www.kroger.com/product/images/xlarge/front/0004133102612"],
  ["45153001",	"COFFEE",	"Green Mountain Coffee Roasters, Inc.",	"Tea & Coffee",	"SUGAR, LEMON JUICE POWDER (CITRIC ACID, SUGAR, LEMON OIL, LEMON JUICE SOLIDS, ASCORBIC ACID), CITRIC ACID, REB A (STEVIA EXTRACT), NATURAL FLAVOR, LEMON PEEL POWDER, LEMON FRUIT POWDER",	68573,	"0.3 kg",	45,	"https://target.scene7.com/is/image/Target/GUEST_592a227e-2479-4b91-b9a0-fbf96fdc7241?wid=488&hei=488&fmt=pjpeg"],
  ["45203094",	"ORGANIC KALE SALAD",	"Harvest Sensations LLC",	"Fruits & Vegetables",	"KALE*, RED CABBAGE* & CARROTS*.",	85199,	"0.3 kg",	13,	"https://www.taylorfarms.com/wp-content/uploads/2016/10/TaylorFarmsOrganic5ozBabyKale.png"],
  ["45031116",	"SALMON",	"High Liner Foods USA Incorporated",	"Meat & Seafood",	"SALMON, WATER, VEGETABLE OIL (CANOLA, COTTONSEED, AND/OR SOYBEAN), CONTAINS 2% OR LESS OF: TOMATO PASTE, RICE STARCH, CITRIC ACID, SALT, DEHYDRATED GARLIC, DEHYDRATED ONION, SPICES, LIME OIL;, NATURAL FLAVORS, SOY LECITHIN, SODIUM TRIPOLYPHOSPHATE (TO RETAIN MOISTURE).",	44469,	"1 kg",	17,	"https://www.curtze.com/images/salmon-hero.png"],
  ["45031109",	"MEDITERRANEAN CRUSTED SALMON",	"High Liner Foods USA Incorporated",	"Meat & Seafood",	"SALMON, WATER, ENRICHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), ENRICHED BLEACHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), MODIFIED CORN STARCH, VEGETABLE OIL (SOYBEAN, CANOLA, AND/OR COTTONSEED OIL), CONTAINS LESS THAN 2% OF THE FOLLOWING: ROMANO CHEESE (SHEEP'S MILK, RENNET, SALT), SUN DRIED TOMATOES, SULFUR DIOXIDE), PINE NUTS, SALT, YELLOW CORN FLOUR, WHITE CORN FLOUR, DISODIUM INOSINATE AND DISODIUM GUANYLATE, EGG WHITES, YEAST EXTRACT, LEAVENING (SODIUM ALUMINUM PHOSPHATE, SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, MONOCALCIUM PHOSPHATE), CORN SYRUP, DEHYDRATED GARLIC, DEHYDRATED ONION, CORN CEREAL (MILLED CORN GRITS), TORULA YEAST, ONION POWDER, CARAMEL COLOR, SPICES, SUGAR, GARLIC POWDER, EXTRACTIVE OF PAPRIKA (COLOR), PARTIALLY HYDROGENATED COTTONSEED AND/OR SOYBEAN OIL, NATURAL AND ARTIFICIAL FLAVOR, TOMATO POWDER, RED 40, YELLOW 6, SODIUM TRIPOLYPHOSPHATE (TO RETAIN MOISTURE), OLIVE OIL, YELLOW 5, BLUE 1, YEAST, SPICE EXTRACTIVES.",	77786,	"1 kg",	58,	"https://seacuisine.imgix.net/media/1116/blackenedranchsalmon_1200x1200_s2_cob.png?w=320&fit=clip&auto=compress"],
  ["45038127",	"TURKEY",	"Hormel Foods Corporation",	"Meat & Seafood",	"MECHANICALLY SEPARATED TURKEY, TURKEY BROTH, CHILI POWDER (CHILI PEPPERS, FLAVORING), CORN FLOUR, OATMEAL, TEXTURED VEGETABLE PROTEIN (SOY FLOUR, CARAMEL COLOR), TOMATOES (WATER, TOMATO PASTE), SUGAR, SALT, HYDROLYZED CORN, SOY, AND WHEAT PROTEIN, FLAVORING, AUTOLYZED YEAST, MODIFIED CORNSTARCH, SPICE, MONOSODIUM GLUTAMATE.",	53863,	"1 kg",	52,	"https://marvel-b1-cdn.bc0a.com/f00000000202513/www.fosterfarms.com/wp-content/uploads/97837-474954-TRKY-CON-TRKYTLS-6P_H.png"],
  ["45212549",	"SOFT & CHEWY COOKIES",	"iBakeFoods",	"Sweets",	"ENRICHED WHEAT FLOUR (FLOUR, NIACIN, REDUCED IRON, THIAMINE, MONONITRATE, RIBOFLAVIN AND FOLIC ACID), SUGAR, SHORTENING (LIQUID AND PARTIALLY HYDROGENATED SOYBEAN OIL, HYDROGENATED COTTONSEED OIL, TBHQ AND CITRIC ACID ADDED TO PROTECT FLAVOR), EGGS, INVERT CORN SYRUP, SALT, BAKING POWDER (SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), NATURAL FLAVOR.",	18785,	"1 pack",	13,	"https://www.keebler.com/globalassets/keebler/products/112_chocolatechip/repeated_number_group/1124_chipsdeluxesoftandchewey/keebler-chips-deluxe-soft-n-chewy-14.8oz-200805.png"],
  ["45004010",	"COOKIES",	"Interbake Foods Inc.",	"Bread & Bakery",	"SUGAR, ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), VEGETABLE SHORTENING (PALM OIL, HYDROGENATED COCONUT AND SOYBEAN OILS, AND PARTIALLY HYDROGENATED PALM KERNEL OIL), CORN SYRUP, COCONUT, SWEETENED CONDENSED MILK (MILK, SUGAR), HIGH FRUCTOSE CORN SYRUP, CONTAINS LESS THAN 2% OF: SORBITOL, DEXTROSE, COCOA (PROCESSED WITH ALKALI), WHEY, GLYCERINE, SALT, SOY LECITHIN, LEAVENING (BAKING SODA, MONOCALCIUM PHOSPHATE), NATURAL AND ARTIFICIAL FLAVOR.",	42608,	"0.22 kg",	30,	"https://www.cookietakeabite.com/wp-content/uploads/2016/09/deluxe-variety-tin.png"],
  ["45150411",	"BABIES COOKIES",	"Jackie's Cookie Connection",	"Bread & Bakery",	"ALL PURPOSE FLOUR, TOLL HOUSE MINI MORSELS MILK CHOCOLATE PURE CANE GOLDE BROWN SUGAR, PURE CANE SUGAR, SALTED BUTTER, EGG, PEANUT BUTTER, SALT, BAKING POWDER, BAKING SODA, PURE VANILLA EXTRACT.",	78464,	"1 pack",	35,	"https://www.gerber.com/media/catalog/product/a/r/arrowroot20biscuits_pcjqu1s45y07unxl.png?quality=80&fit=bounds&height=265&width=265&canvas=265:265"],
  ["45365529",	"WHITE EGGS",	"KREHER",	"Dairy, Eggs & Cheese",	"EGGS",	78589,	"1 pack",	22,	"https://cdn.happyegg.com/static/happyegg_web/happyegg-frontend/dist/img/cartons/free-range/4.png"],
  ["45052448",	"SAUSAGE",	"La Tortilleria",	"Meat & Seafood",	"PORK, NATURAL SPICES, SALT, VINEGAR, PAPRIKA, FLAVORINGS, SODIUM NITRITE.",	48729,	"1 kg",	91,	"https://www.beyondmeat.com/wp-content/uploads/BeyondSausageBrat_PKG_Render_734x553-1-1.png"],
  ["45057070",	"CHIPOTLE BAR-B-Q SAUCE",	"Lady Walton's Cookies, Inc.",	"Sauces",	"TOMATO PUREE (TOMATO PASTE, WATER), SUGAR, MOLASSES, DISTILLED VINEGAR, SOY SAUCE (WATER, WHEAT, SOYBEANS, SALT), BACON BITS (PORK, SEA SALT, RAW SUGAR, SPICES), SALT, CHIPOTLE PEPPER FLAKES, DRIED GARLIC, DRIED ONION, SPICES.",	61720,	"1 pack",	2,	"https://headcountry.com/wp-content/uploads/2017/01/01160344/products-sauce.png"],
  ["45089313",	"BEEF",	"Land O'Frost, Inc.",	"Meat & Seafood",	"BEEF, WATER, SALT. LESS THAN 2% OF FLAVORINGS, BLACK PEPPER, SUGAR, CORN SYRUP, SODIUM PHOSPHATES, SODIUM ERYTHORBATE, SODIUM NITRITE.",	41543,	"1 kg",	29,	"https://proman.com.ua/wp-content/uploads/2017/04/beef.png"],
  ["45046937",	"POPCORN",	"LESSEREVIL",	"Snacks",	"ORGANIC NON-GMO POPCORN, ORGANIC EVAPORATED CANE SUGAR, ORGANIC BROWN RICE SYRUP, ORGANIC COCONUT OIL, HIMALAYAN SALT, ORGANIC SUNFLOWER LECITHIN.",	12230,	"1 pack",	18,	"https://jimmys.eu/wp-content/uploads/Family-bags_v2-1.png"],
  ["45363190",	"CLEMENTINE",	"LGS Specialty Sales, Ltd",	"Fruits & Vegetables",	"CLEMENTINE",	73084,	"1 kg",	50,	"https://www.lgssales.com/wp-content/uploads/2017/09/darling-clementines-1.png"],
  ["45041515",	"LINDT, LINDOR, MILK CHOCOLATE TRUFFLES",	"Lindt & Sprungli Schweiz AG",	"Sweets",	"MILK CHOCOLATE [SUGAR, COCOA BUTTER, MILK, CHOCOLATE, SOYA LECITHIN (EMULSIFIER), BARLEY MALT POWDER, VANILLIN (ARTIFICIAL FLAVORING)], VEGETABLE OIL (COCONUT, PALM KERNEL), SUGAR, MILK, CHOCOLATE, COCOA BUTTER, SOYA LECITHIN (EMULSIFIER), BARLEY MALT POWDER, ARTIFICIAL FLAVORS.",	43278,	"1 pack",	93,	"https://www.lindt.co.uk/media/catalog/product/l/i/lindt-lindor-milk-mini-truffles-80g-out-of-pack.png?quality=80&fit=bounds&height=700&width=700&canvas=700:700"],
  ["45186696",	"ORANGES",	"Lone Star Citrus Growers",	"Fruits & Vegetables",	"ORANGES",	27693,	"1 kg",	49,	"https://crockettfarms.com/assets/img/products/TCMAN_CENTER.png"],
  ["45046111",	"LOWES FOODS, PASTA SAUCE, MUSHROOM",	"Lowe's Food Stores, Inc.",	"Sauces",	"TOMATO PUREE (WATER, TOMATO PASTE), MUSHROOMS, SUGAR, SALT, SOYBEAN OIL, DEHYDRATED ONIONS, GARLIC, SPICES, PECORINO ROMANO CHEESE (PASTEURIZED SHEEP'S MILK, SALT, CHEESE CULTURE, ENZYMES), EXTRA VIRGIN OLIVE OIL.",	17042,	"1 pack",	46,	"https://www.bertolli.com/wp-content/uploads/2017/07/BertRusticCut_RoastedGarlic-400x400-c-default.png"],
  ["45216105",	"SMOKED PORK SAUSAGE",	"Man Packing Co, LLC",	"Meat & Seafood",	"PORK, WATER, SALT, CORN SYRUP, DEXTROSE, SUGAR, SODIUM PHOSPHATE, PAPRIKA, FLAVORINGS, SODIUM ERYTHORBATE, AUTOLYZED YEAST EXTRACT, SODIUM NITRITE.",	15338,	"1 kg",	94,	"https://www.johnsonville.com/.imaging/mte/johnsonville-retail/640-wide/dam/johnsonville/product-images/smoked-brats/jcr:content/smoked-brats.png"],
  ["45001584",	"SWISS CHEESE",	"Milton G. Waldbaum Company",	"Dairy, Eggs & Cheese",	"PASTEURIZED PART-SKIM MILK, CHEESE CULTURE, SALT, ENZYMES, NATAMYCIN (MOLD INHIBITOR).",	37678,	"0.5 kg",	87,	"https://img.pngio.com/emmentaler-swiss-cheese-1-pound-chunk-free-shipping-frank-and-sal-chunk-of-cheese-png-1000_800.png"],
  ["45015429",	"OLIVE OIL",	"NAPA VALLEY NATURALS",	"Sauces",	"100% COLD PRESSED UNREFINED EXTRA VIRGIN OLIVE OIL.",	37204,	"0.5 kg",	78,	"https://cdn.shopify.com/s/files/1/2400/9633/products/Truly-Bottle_v2_1200x1200.png?v=1588911366"],
  ["45202946",	"GRAPES",	"Naturipe Farms, LLC",	"Fruits & Vegetables",	"GRAPES",	35339,	"1 kg",	82,	"https://www.stollerukraine.com.ua/assets/images/vinograd-prod.png"],
  ["45202947",	"BLUEBERRY",	"Naturipe Farms, LLC",	"Fruits & Vegetables",	"BLUEBERRIES",	33281,	"0.5 kg",	60,	"https://samozamesrus.ru/image/cache/catalog/tpa1/blueberries-500x500.png"],
  ["45294001",	"NESCAFE, HAZELNUT",	"Nestle USA Inc.",	"Tea & Coffee",	"SUGAR, CORN SYRUP, HYDROGENATED VEGETABLE OIL (COCONUT AND PALM KERNEL AND/OR SOYBEAN), SOLUBLE COFFEE, LESS THAN 2% OF NATURAL AND ARTIFICIAL FLAVOR, SODIUM CASEINATE (A MILK DERIVATIVE), DIPOTASSIUM PHOSPHATE, SODIUM HEXAMETAPHOSPATE SODIUM ALUMINOSILICATE, MONO - AND DIGLYCERIDES, ANNATTO COLOR.",	89333,	"1 pack",	1,	"https://i.ebayimg.com/images/g/bdAAAOSwGjldFEHQ/s-l300.png"],
  ["45212537",	"TOMATO",	"Newgem Foods, LLC",	"Fruits & Vegetables",	"TOMATO PASTE (TOMATOES), APPLE PUREE CONCENTRATE (APPLES, ASCORBIC ACID), VEGETABLE GLYCERINE, SOY PROTEIN ISOLATE, POWDERED CELLULOSE, FRUIT PECTIN, CHIPOTLE PUREE (PEPPERS, WATER, SALT, VINEGAR, CITRIC ACID), WATER, SORBITOL.",	78061,	"1 kg",	93,	"https://www.levarht.com/wp-content/uploads/2018/05/49-Cherry-tomatoes-800x533.png"],
  ["45114822",	"BANANAS",	"NEXT ORGANICS",	"Fruits & Vegetables",	"ORGANIC DARK CHOCOLATE (ORGANIC CHOCOLATE LIQUOR, ORGANIC CANE SUGAR, ORGANIC COCOA BUTTER, SOY LECITHIN (NON-GMO), ORGANIC VANILLA EXTRACT), ORGANIC BANANA, ORGANIC CONFECTIONER'S GLAZE (ORGANIC MALTODEXTRIN, ORGANIC SUCROSE, SHELLAC).",	70186,	"1 kg",	27,	"https://www.zebrabananas.com/wpzb/wp-content/uploads/2019/12/Zebra_Banana_Sticker-mockup-1.png"],
  ["45002246",	"100% ORANGE JUICE",	"Ocean Spray Cranberries, Inc.",	"Beverages",	"ORANGE JUICE (WATER, ORANGE JUICE CONCENTRATE)",	10057,	"1 L",	76,	"https://www.checkers.co.za/medias/10511311EA-20190726-Media-checkers515Wx515H?context=bWFzdGVyfGltYWdlc3wyMTU0OTF8aW1hZ2UvcG5nfGltYWdlcy9oNmYvaDI5Lzg4NTk2Mzc5NzMwMjIucG5nfDEzN2E0MTFjNTA5NzQyZjI1NGNiM2JjZmUxMDUxNzUwOTI4ZDBiYzNjZjFhOGQ2YjY1NjNlNjk3NGNjMTVlNTE"],
  ["45052447",	"CHORIZO SAUSAGE",	"Ole Mexican Foods, Inc.",	"Meat & Seafood",	"PORK, NATURAL SPICES, SALT, VINEGAR, PAPRIKA, FLAVORINGS, SODIUM NITRITE.",	22690,	"1 pack",	80,	"https://www.johnsonville.com/.imaging/mte/johnsonville-retail/640-wide/dam/johnsonville/product-images/chorizo/jcr:content/chorizo.png"],
  ["45048183",	"SHRIMP",	"PACIFIC SURF",	"Meat & Seafood",	"SODIUM TRIPOLYPHOSPHATE",	5691,	"1 pack",	84,	"https://17idjc2mjkuw17g32z1ivim6-wpengine.netdna-ssl.com/wp-content/uploads/Langoustine_Shrimp-650x650.png"],
  ["45369405",	"Pepsi 12 Fluid Ounce Glass Bottle",	"PepsiCo",	"Beverages",	"Carbonated Water, Sugar, Caramel Color, Phosphoric Acid, Caffeine, Natural Flavor.",	47769,	"0.5 L",	8,	"https://freepngimg.com/thumb/pepsi_logo/32615-8-pepsi-logo-hd.png"],
  ["45004230",	" CHICKEN BREAST",	"PERDUE BRAND",	"Meat & Seafood",	"Fresh boneless, skinless chicken breast",	95449,	"1 kg",	28,	"https://www.shoprite.co.za/medias/10542936KG-20190726-Media-checkers300Wx300H?context=bWFzdGVyfGltYWdlc3wxMzE5MDJ8aW1hZ2UvcG5nfGltYWdlcy9oY2MvaGQwLzg4NTk5MDkwMjk5MTgucG5nfDllNjg3YzVhMTE1YjZhYWY4MTA3NGU1M2RhYTQwYzNjN2M1NjVlMDI3NjkyNjk5ZjAwYWQ5MGFiYzA3YWE0ZjU"],
  ["45212531",	"BULGUR",	"PEREG",	"Grains, Pasta & Sides",	"BULGUR (CONTAINS GLUTEN)",	56793,	"1 kg",	93,	"https://fasol.tv/upload/iblock/8b1/8b1d89183739eebf5559acdf91fc14bd.png"],
  ["45212528",	"BASMATI RICE",	"PEREG",	"Grains, Pasta & Sides",	"BASMATI RICE.",	11311,	"1 kg",	81,	"https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_3.0,f_auto,q_auto:low,w_400/41933-sil-ingredients-daawat-basmati-rice"],
  ["45238507",	"SUPERIOR GINGER ALE",	"Q GINGER",	"Beverages",	"CARBONATED WATER, ORGANIC AGAVE, GINGER EXTRACT, EXTRACTS OF LEMON JUICE CORIANDER, CARDAMOM, CAYENNE, ORANGE PEEL, ROSE OIL.",	77263,	"1 L",	95,	"https://www.mancunianfoods.com/wp-content/uploads/2019/04/812-large_default.jpg"],
  ["45235884",	"CREAM",	"Quesos La Ricura",	"Dairy, Eggs & Cheese",	"PASTEURIZED HEAVY CREAM, CREAM CHEESE (PASTEURIZED CULTURED MILK AND CREAM, WHEY, SALT, LOCUST BEAN GUM), SOUR CREAM (CULTURED MILK, CREAM, MODIFIED FOOD STARCH, SODIUM CITRATE, CARRAGEENAN, GUAR GUM, LOCUST BEAN GUM), SALT, ANNATTO (FOR COLOR).",	27815,	"0.5 kg",	37,	"https://storcpdkenticomedia.blob.core.windows.net/media/lolretail/media/lolr-media/products/whipped-cream-collage-600.png?ext=.png"],
  ["45203100",	"CHIK'N TENDERS",	"Quorn Foods Inc.",	"Meat & Seafood",	"MYCOPROTEIN (88%), POTATO PROTEIN, PEA FIBER. CONTAINS 2% OR LESS OF CALCIUM CHLORIDE & CALCIUM ACETATE (FIRMING AGENTS), WATER, NATURAL FLAVORING, WHEAT GLUTEN, CARRAGEENAN & SODIUM ALGINATE (STABILIZERS).", 1299, "1 kg", 20, 	"https://www.gardein.com/sites/g/files/qyyrlu701/files/images/products/nashville-hot-chickn-tenders-51204.png"],
  ["45048168",	"ITALIAN SAUSAGE",	"RANA",	"Meat & Seafood",	"FILLING (ITALIAN SAUSAGE (PORK, WATER, SPICES, SALT, SUGAR), RICOTTA (WHEY, WHOLE MILK, CREAM, VINEGAR), PARMESAN CHEESE (PASTEURIZED CULTURED MILK, SALT, ENZYMES), MOZZARELLA CHEESE (PASTEURIZED CULTURED MILK, SALT AND ENZYMES), CHICORY ROOT FIBER, HEAVY CREAM (CREAM), ROASTED ONION, MASCARPONE CHEESE (PASTEURIZED MILK, CREAM, CITRIC ACID), BREAD CRUMBS (WHEAT FLOUR, YEAST, SALT), 2% OR LESS OF POTATO STARCH, WHEY, VEGETABLE FIBER, SALT, GARLIC, NATURAL FLAVORS, BLACK PEPPER). PASTA (SEMOLINA, EGGS, WATER).",	60149,	"1 pack",	18,	"https://www.beyondmeat.com/wp-content/uploads/BeyondSausageHotItalian_PKG_Render_734x553-1-1.png"],
  ["45031065",	"SALADA, GREEN TEA",	"Redco Foods, Inc.",	"Tea & Coffee",	"GREEN TEA, CALCIUM LACTATE, NATURAL CHERRY FLAVOR, HIBISCUS, RED CLOVER, ASCORBIC ACID, LEMONGRASS.",	55002,	"1 pack",	19,	"https://i5.walmartimages.com/asr/89a33c5b-2b2c-4ffa-af80-12108d4dcb67.dcd648e2b829bf40e85f9685bed2bf45.png?odnWidth=612&odnHeight=612&odnBg=ffffff"],
  ["45209709",	"KIWI",	"REGAL GOURMET SNACKS",	"Fruits & Vegetables",	"KIWI, SUGAR, CITRIC ACID, SULPHUR DIOXIDE, FD&C YELLOW #5, AND FD&C BLUE #1.",	89808,	"1 kg",	94,	"https://www.teisseire.com/media/1739/kiwipng.png"],
  ["45012124",	"COTTAGE CHEESE SMALL CURD",	"ROUNDY'S",	"Dairy, Eggs & Cheese",	"CULTURED SKIM MILK, WHEY PROTEIN CONCENTRATE, CREAM, SKIM MILK, CONTAINS 2% OR LESS OF SALT, GUAR GUM, MONO AND DIGLYCERIDES, LOCUST BEAN GUM, XANTHAN GUM, NATURAL FLAVORS, POTASSIUM SORBATE AND CARBON DIOXIDE (PRESERVATIVES), CARRAGEENAN, POLYSORBATE 80, ENZYMES.",	76263,	"0.3 kg",	14,	"https://producersdairy.com/wp-content/uploads/2020/11/SmallCurdCC_Grouped.png"],
  ["45054027",	"VAN KAAS, GOUDA CHEESE",	"Russell McCall's Inc.",	"Dairy, Eggs & Cheese",	"PASTEURIZED MILK, CHEESE CULTURES, SALT, ENZYMES, ANNATTO.",	17241,	"0.5 kg",	77,	"https://veldhuyzenkaas.nl/wp-content/uploads/2017/01/comp-bluel-min.png"],
  ["45152996",	"RIPPLE POTATO CHIPS",	"Save Mart Supermarkets Inc.",	"Snacks",	"POTATOES, VEGETABLE OIL (CORN AND/OR SUNFLOWER AND/OR CANOLA), SALT.",	98010,	"1 pack",	18,	"https://dtgxwmigmg3gc.cloudfront.net/imagery/assets/derivations/icon/512/512/true/eyJpZCI6IjFlMmY0MDI1MDEyZmJhMTc2OThiMmUzMGQ0NGRjY2ZiIiwic3RvcmFnZSI6InB1YmxpY19zdG9yZSJ9?signature=6d2ffcbd05e4e00fcb0efa449cfea94b210759e07e32bd78a59ad6bd31f5507a"],
  ["45150414",	"GUMMY",	"SNAP INFUSION LLC",	"Sweets",	"ORGANIC SUGAR, TAPIOCA SYRUP, PECTIN, CITRIC ACID, CONTAINS 2% OR LESS OF THE FOLLOWING: NATURAL FLAVORS POTASSIUM PHOSPHATE, CALCIUM PHOSPHATE, ASCORBIC ACID (VITAMIN C), D-ALPHA TOCOPHERYL ACETATE (VITAMIN E), CALCIUM D-PANTOTHENATE (VITAMIN B5), PYRIDOXINE HYDROCHLORIDE (VITAMIN B6), CYANOCOBALAMIN (VITAMIN B12), BIOTIN, NATURAL COLORS.",	40745,	"1 pack",	44,	"https://i.pinimg.com/originals/df/38/73/df3873d0a7a22da17a1b7e431aa68ec0.png"],
  ["45015395",	"SUNFLOWER OIL",	"SPECTRUM CULINARY",	"Sauces",	"EXPELLER PRESSED REFINED HIGH OLEIC ORGANIC SUNFLOWER OIL*, ORGANIC CANE ALCOHOL, ORGANIC SOY LECITHIN, PROPELLANT.",	30657,	"1 pack",	7,	"https://purepng.com/public/uploads/large/purepng.com-sunflower-oilsunflower-oilcooking-oilfrying-oilnon-volatile-oil-1411529833012ojmrn.png"],
  ["45030077",	"LA PASTA, MUSHROOM RAVIOLI",	"Spring Valley Water Co.",	"Grains, Pasta & Sides",	"FILLING INGREDIENTS: PORTOBELLO MUSHROOM, RICOTTA CHEESE (PASTEURIZED WHOLE MILK, VINEGAR, SALT), CRIMINI MUSHROOMS, MOZZARELLA CHEESE (PASTEURIZED MILK, CHEESE CULTURES, SALT, ENZYMES POWDERED CELLULOSE TO PREVENT CAKING), PARMESAN CHEESE (PASTEURIZED PART-SKIM MILK, CHEESE CULTURES, SALT, ENZYMES, POWDERED CELLULOSE TO PREVENT CAKING), ONIONS, DEHYDRATED POTATOES, SEA SALT, FRESH PARSLEY, EXTRA VIRGIN OLIVE OIL, FRESH THYME, BLACK PEPPER. PASTA INGREDIENTS: CORN STARCH, POTATO STARCH, POTATO FLAKES (DEHYDRATED POTATOES, MONO AND DIGLYCERIDES, ASCORBIC ACID, CITRIC ACID), TAPIOCA STARCH, XANTHAN GUM, WHOLE DRIED EGGS, FILTERED WATER AND SEA SALT.",	90763,	"1 pack",	61,	"https://rana-cdn.thron.com/delivery/public/image/rana/0cb0376a-0c01-4489-bc6c-9817e0f4031d/gg3i3t/std/0x0/PROD_AUSTRALIA_-porcini"],
  ["45225265",	"BROCCOLI",	"Supervalu, Inc.",	"Fruits & Vegetables",	"BROCCOLI.",	7650,	"0.5 kg",	2,	"https://www.birdseye.com/sites/g/files/qyyrlu756/files/images/products/broccoli-florets-54082.png"],
  ["45225266",	"BRUSSELS SPROUTS",	"Supervalu, Inc.",	"Fruits & Vegetables",	"BRUSSELS SPROUTS.",	86360,	"1 kg",	76,	"https://www.levarht.com/wp-content/uploads/2018/05/29-Brussels-sprouts-800x687.png"],
  ["45238518",	"SPARKLING SPRING WATER",	"Talking Rain Beverage Co., Inc",	"Beverages",	"CARBONATED MOUNTAIN SPRING WATER, NATURAL FLAVORS.",	33192,	"1 L",	38,	"https://www.polandspring.com/sites/g/files/xknfdk936/files/styles/lipp_desktop/public/2020-01/PolandSpring_SimplyBubbles_NutritionalInformation.png?itok=AUL9K6He"],
  ["45375156",	"Sprite Bottle, 1.75 Liters",	"The Coca-Cola Company",	"Beverages",	"CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, CITRIC ACID, NATURAL FLAVORS, SODIUM CITRATE, SODIUM BENZOATE (TO PROTECT TASTE).",	6000,	"1.75 L",	5,	"https://webstockreview.net/images/sprite-bottle-png-3.png"],
  ["45375157",	"Fanta Berry Soda Bottle, 2 Liters",	"The Coca-Cola Company",	"Beverages",	"CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, NATURAL FLAVORS, CITRIC ACID, SODIUM CITRATE, MALIC ACID, POTASSIUM SORBATE AND SODIUM BENZOATE (TO PROTECT TASTE), BLUE 1.",	86957,	"2 L",	8,	"https://cdn.shopify.com/s/files/1/0270/6410/7107/products/Screen-Shot-2019-11-06-at-9.15.13-PM_600x.gif?v=1573093319"],
  ["45022220",	"PROBIOTIC LOWFAT YOGURT WITH BIFIDUS",	"The Dannon Company, Inc.",	"Dairy, Eggs & Cheese",	"CULTURED GRADE A REDUCED FAT MILK, CANE SUGAR, WATER, PINEAPPLE, INULIN, MODIFIED FOOD STARCH, CONTAINS LESS THAN 1% OF ROLLED WHITE WHEAT FLAKES, RED WHEAT BRAN, MILK PROTEIN CONCENTRATE, KOSHER GELATIN, ROLLED OATS, NATURAL FLAVOR, AGAR AGAR, CITRIC ACID, SODIUM CITRATE, VITAMIN D3, TURMERIC (FOR COLOR).",	79778,	"0.33 L",	10,	"https://vaalia.com.au/wp-content/uploads/2020/09/Vaalia-4Pack-Blueberry-Carton-3D-e1601062324873.png"],
  ["45057076",	"ORGANIC TOMATO KETCHUP",	"Topco Associates, Inc.",	"Sauces",	"ORGANIC TOMATO CONCENTRATE (WATER AND ORGANIC TOMATO PASTE), ORGANIC SUGAR, ORGANIC VINEGAR, SALT, ORGANIC ONION POWDER, ORGANIC SPICE.",	17961,	"1 pack",	93,	"https://wholesome.bio/wp-content/uploads/2018/09/ketchup-1000x1000.png"],
  ["45324279",	"100% JUICE FROM CONCENTRATE",	"Tropicana Products, Inc.",	"Beverages",	"100% APPLE JUICE FROM CONCENTRATE (FILTERED WATER AND CONCENTRATED APPLE JUICE), NATURAL FLAVORS, MALIC ACID AND ASCORBIC ACID (VITAMIN C).",	88881,	"1 L",	23,	"https://s3.us-east-2.amazonaws.com/jms-s3-mkt-consumer-p-pmc6/tmp/image-thumbnails/santacruzorganic/products/juices/image-thumb__5553__auto_fa68343f5007a86f2d6840001181fd80/SCO-TartCherryConcentrate-1920x1920.png"],
  ["45015047",	"MOUNTAIN WHITE BREAD",	"United States Bakery",	"Bread & Bakery",	"WATER, BROWN RICE FLOUR, TAPIOCA STARCH, TAPIOCA SYRUP, WHOLE GRAIN SORGHUM FLOUR, XANTHAN GUM, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: WHOLE EGGS, WHOLE GRAIN AMARANTH SEED, EXTRA VIRGIN OLIVE OIL, SALT, CULTURED RICE FLOUR, YEAST, ENZYMES.",	49679,	"0.5 kg",	43,	"https://www.shoprite.co.za/medias/10136370EAv2-checkers300Wx300H?context=bWFzdGVyfGltYWdlc3w1MjE3NXxpbWFnZS9wbmd8aW1hZ2VzL2g1NC9oNWIvOTI3ODc1MjUyMjI3MC5wbmd8NWFlMTQ3NDliZjBmYmRmOWQ1MWE0ZjE5YjgzZWUxMGY2NGM4OTBjMjViOTc0ODg4MmNiZWRhMjEzNGNiNTQyMQ"],
  ["45015048",	"BREAD",	"United States Bakery",	"Bread & Bakery",	"WATER, BROWN RICE FLOUR, TAPIOCA STARCH, TAPIOCA SYRUP, WHOLE GRAIN SORGHUM FLOUR, XANTHAN GUM, WHOLE GRAIN MILLET SEEDS, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: WHOLE EGGS, WHOLE GRAIN MILLET FLOUR, WHOLE GRAIN AMARANTH SEED, WHOLE GRAIN TEFF SEEDS, RED QUINOA SEEDS, EXTRA VIRGIN OLIVE OIL, MOLASSES, SALT, CULTURED RICE FLOUR, YEAST, ENZYMES.",	18292,	"0.5 kg",	2,	"https://cdn.shopify.com/s/files/1/0249/9670/8405/products/OatBread_NOPackaging_Badge_1200x.png?v=1570045780"],
  ["45015394",	"POTATO CHIPS",	"UTZ Quality Foods, Inc.",	"Snacks",	"POTATOES, LARD (WITH TBHQ AND BHT ADDED TO HELP PROTECT FLAVOR), SALT, SUGAR, DEXTROSE, MALTODEXTRIN (DERIVED FROM CORN), RICE FLOUR, TORULA YEAST, NATURAL AND ARTIFICIAL FLAVORS, DRIED ONION, SPICES, VINEGAR, CITRIC ACID, CARAMEL (COLOR), SMOKED TORULA YEAST, AUTOLYZED YEAST EXTRACT, DRIED GARLIC, BEET POWDER (COLOR), DRIED HORSERADISH, BACON FAT, NATURAL SMOKE FLAVOR, SUNFLOWER OIL, DISODIUM INOSINATE AND DISODIUM GUANYLATE.",	6365,	"0.15 kg",	69,	"https://d2aam04nmhpdf8.cloudfront.net/images/images/000/038/378/xlarge/20828_1.png?1597098627"],
  ["45365542",	"LARGE EGGS",	"Walgreens Co.",	"Dairy, Eggs & Cheese",	"EGGS",	57998,	"1 pack",	51,	"https://www.bandpwholesale.co.uk/images/ww/products-6/PLU%204%2011%20LGE%20MED%20EGGS.png"],
  ["45183679",	"STRAWBERRIES",	"Wegmans Food Markets, Inc.",	"Fruits & Vegetables",	"ORGANIC STRAWBERRIES.",	73391,	"0.5 kg",	89,	"https://www.cascadianfarm.com/wp-content/uploads/2018/12/Strawberries_Main_0218.png"],
  ["45183676",	"MINI SWEET PEPPERS",	"Wegmans Food Markets, Inc.",	"Fruits & Vegetables",	"RED, ORANGE AND YELLOW SWEET PEPPERS.",	77297,	"0.5 kg",	53,	"https://www.perofamilyfarms.com/wp-content/uploads/2017/10/conv_mini_sweet_peppers_with_product_16oz.png"],
  ["45054023",	"SUGAR",	"Weis Markets, Inc.",	"Grains, Pasta & Sides",	"SUGAR, CORN STARCH.",	10,	"1 kg",	57,	"https://uploads-ssl.webflow.com/5ac245033a6295f837d8702c/5ae87ad9ee38f191f4b89868_organic-cane-sugar-cinnamon-c.png"],
  ["45054030",	"MARSHMALLOWS",	"Weis Markets, Inc.",	"Sweets",	"CORN SYRUP, SUGAR, MODIFIED CORN STARCH, GELATIN, WATER, TETRASODIUM PHOSPHATE, NATURAL AND ARTIFICIAL FLAVOR, COLOR (BLUE 1).",	93149,	"0.5 kg",	35,	"https://www.heavenlydelights.com/pub/media/catalog/product/cache/1/image/1000x1320/e9c3970ab036de70892d86c6d221abfe/h/e/heavenly-mallows-140g.png"],
  ["45238491",	"ORGANIC SPARKLING ITALIAN SODA",	"Western Family Foods, Inc.",	"Beverages",	"CARBONATED WATER, ORGANIC SUGAR, ORGANIC APPLE AND POMEGRANATE JUICE FROM CONCENTRATE, CITRIC ACID, NATURAL POMEGRANATE FLAVOR, ORGANIC BLACK CARROT JUICE FROM CONCENTRATE (FOR COLOR).",	28056,	"1 L",	11,	"https://cdn.shopify.com/s/files/1/0007/6818/0342/products/San_Pellegrino_Organic_Blood_Orange_Sparkling_Beverage_Aranciata_Rossa_1024x1024_clipped_rev_1_800x.png?v=1598642116"],
  ["45256944",	"GREEK YOGURT",	"Yoplait USA",	"Dairy, Eggs & Cheese",	"FAT FREE YOGURT (CULTURED PASTEURIZED GRADE A NONFAT MILK, FRUCTOSE, KOSHER GELATIN, LACTIC ACID ESTERS OF MONO AND DIGLYCERIDES, LIME JUICE CONCENTRATE, MODIFIED CORN STARCH, SODIUM CITRATE, POTASSIUM SORBATE ADDED TO MAINTAIN FRESHNESS, NATURAL FLAVOR, YOGURT CULTURES [L. BULGARICUS, S. THERMOPHILUS], FRUIT JUICE AND TURMERIC EXTRACT [FOR COLOR], ACESULFAME POTASSIUM, SUCRALOSE, VITAMIN A ACETATE, VITAMIN D3), NITROGEN.",	19978,	"0.33 L",	66,	"https://www.qbfood.com.sg/pub/media/catalog/product/cache/497447f7b36edae87c3746461ae2789f/a/u/authentic-greek-yogurt-10-150g.png"],
  ["45256950",	"ORIGINAL LOW FAT YOGURT",	"Yoplait USA",	"Dairy, Eggs & Cheese",	"GRAPEFRUIT INGREDIENTS: CULTURED PASTEURIZED GRADE A REDUCED FAT MILK, SUGAR, MODIFIED CORN STARCH, GRAPEFRUIT JUICE CONCENTRATE, KOSHER GELATIN, HONEY, VEGETABLE JUICE (FOR COLOR), PECTIN, NATURAL FLAVOR, VITAMIN A ACETATE, COLORED WITH ANNATTO EXTRACT, VITAMIN D3. VANILLA INGREDIENTS: CULTURED PASTEURIZED GRADE A REDUCED FAT MILK, SUGAR, MODIFIED CORN STARCH, KOSHER GELATIN, NATURAL FLAVOR, VITAMIN A ACETATE, VITAMIN D3. CONTAINS LIVE AND ACTIVE CULTURES",	44271,	"0.33 L",	12,	"https://www.lightandfit.com/wp-content/uploads/2017/02/Vanilla_ss_fruit-1.png"]
];

getData().then(res => {
  for (let prod of res) {
    db.Product.create(prod)
  }
}).catch(console.log);
